### ISSUE TITLE
Build failing in Unreal 5.2 due to CoreUtility "CUBlueprintLibrary.cpp"

### ISSUE THREAD

**Issue by pascalbayer** [getnamo/SocketIOClient-Unreal#378]
Plugin Build on Unreal 5.2 is currently failing with the following errors in CoreUtility "CUBlueprintLibrary.cpp":

```
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(81): error C2065: "BytesToTextureCommand": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(81): error C3861: "ENQUEUE_RENDER_COMMAND": Bezeichner wurde nicht gefunden.
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(85): error C2027: Verwendung des undefinierten Typs "FTextureResource"
UATHelper: Package Plugin Task (Windows): UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h(1396): note: Siehe Deklaration von "FTextureResource"
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(81): error C2065: "ENQUEUE_RENDER_COMMAND": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(127): error C3861: "SerializeWaveFile": Bezeichner wurde nicht gefunden.
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(143): error C2065: "FWaveModInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(143): error C2146: Syntaxfehler: Fehlendes ";" vor Bezeichner "WaveInfo"
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(143): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(145): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(155): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(155): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(212): error C3861: "SerializeWaveFile": Bezeichner wurde nicht gefunden.
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(263): error C2065: "FWaveModInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(263): error C2146: Syntaxfehler: Fehlendes ";" vor Bezeichner "WaveInfo"
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(263): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(266): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(269): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(269): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(269): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(272): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(279): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(280): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(286): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(286): error C2065: "WaveInfo": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(286): error C2660: "USoundWaveProcedural::QueueAudio": Funktion akzeptiert keine 1 Argumente
UATHelper: Package Plugin Task (Windows): UE_5.2\Engine\Source\Runtime\Engine\Classes\Sound\SoundWaveProcedural.h(78): note: Siehe Deklaration von "USoundWaveProcedural::QueueAudio"
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(364): error C2065: "BytesToTextureAsyncCommand": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(364): error C3861: "ENQUEUE_RENDER_COMMAND": Bezeichner wurde nicht gefunden.
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(368): error C2027: Verwendung des undefinierten Typs "FTextureResource"
UATHelper: Package Plugin Task (Windows): UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h(1396): note: Siehe Deklaration von "FTextureResource"
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(364): error C2065: "ENQUEUE_RENDER_COMMAND": nichtdeklarierter Bezeichner
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(392): error C2027: Verwendung des undefinierten Typs "FTexture2DMipMap"
UATHelper: Package Plugin Task (Windows): UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h(739): note: Siehe Deklaration von "FTexture2DMipMap"
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(393): error C2027: Verwendung des undefinierten Typs "FTexture2DMipMap"
UATHelper: Package Plugin Task (Windows): UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h(739): note: Siehe Deklaration von "FTexture2DMipMap"
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(396): error C2027: Verwendung des undefinierten Typs "FTexture2DMipMap"
UATHelper: Package Plugin Task (Windows): UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h(739): note: Siehe Deklaration von "FTexture2DMipMap"
UATHelper: Package Plugin Task (Windows): CUBlueprintLibrary.cpp(403): error C2027: Verwendung des undefinierten Typs "FTexture2DMipMap"
UATHelper: Package Plugin Task (Windows): UE_5.2\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h(739): note: Siehe Deklaration von "FTexture2DMipMap"
```

**Comment by krumiaa** [comment]
getting the same error when compiling, any ideas whats causing this? wondering if it could be specific to the build tools version of Microsoft Visual Studio, Im using Using Visual Studio 2022 14.30.30709

**Comment by pascalbayer** [comment]
Just tested this and I'm also still getting these errors with the version 2.6.0

**Comment by getnamo** [comment]
What platform is used for build?

**Comment by pascalbayer** [comment]
Resolved the build issue by adding the following missing header imports in `CoreUtility/Private/CUBlueprintLibrary.cpp`:
```cpp
#include "RenderingThread.h"
#include "TextureResource.h"
#include "Audio.h"
```

**Comment by getnamo** [comment]
That's interesting, what platform/build command are you using that was spitting out errors? I'm trying to replicate these, but I don't seem to be getting the same errors as others.

**Comment by getnamo** [comment]
https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.7.1 should work for both 5.2 and 5.3. Re-open issue if that release doesn't work for you.
