### ISSUE TITLE
unqualified call to 'std::move' UE5.1 and MacOS

### ISSUE THREAD

**Issue by beuman** [getnamo/SocketIOClient-Unreal#375]
Hello, I am having the following issue when trying to build the project wich was working fine few days ago :

`  sio_message.h(208, 38): unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]`
  
  I get this error everywhere this function is called. Interesting to note there's also another error :
  
` WindowsPlatformApplicationMisc.h(42, 5): 'WINDOWS_USE_FEATURE_APPLICATIONMISC_CLASS' is not defined, evaluates to 0 [-Werror,-Wundef]`
 
 I have latest macOS, Xcode (only used to generate project files), and Rider version. Using UE5.1.

**Comment by beuman** [comment]
From my Windows computer, when trying to package for Android I also get the following issue :
` WindowsPlatformApplicationMisc.h(42, 5): 'WINDOWS_USE_FEATURE_APPLICATIONMISC_CLASS' is not defined, evaluates to 0 [-Werror,-Wundef]`

**Comment by beuman** [comment]
Using the master branch :
```
"FileVersion": 3,
"Version": 1,
"VersionName": "2.5.8",
"EngineVersion": "5.1"
```

**Comment by getnamo** [comment]
Looks like it complains about: https://github.com/getnamo/SocketIOClient-Unreal/blob/master/Source/SocketIOLib/Public/sio_message.h#L208 and the second line is not referenced inside the plugin so may not be related.

For the first error you can try to remove the `move()` wrapper around `v` so it should just be `_v(v)`. I've never seen the issue before but it's possible a new compiler version for Mac might be more strict, this is typically a warning and not an error though and usually compiles through otherwise.

**Comment by getnamo** [comment]
See if https://github.com/getnamo/SocketIOClient-Unreal/tree/Stdmove fixed the warning error for you

**Comment by staskjs** [comment]
I had the same issue after upgrading from 5.1 to 5.2. Adding std:: to move helped.

**Comment by mikeseese** [comment]
This error also happens for cross compiling for Linux. I implemented the changes in `stdmove` myself and that did fix the compilation errors.

**Comment by mikeseese** [comment]
This was fixed in #376 and should be closed
